// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $index from "./routes/index.tsx";
import * as $HelloWorld from "./islands/HelloWorld.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/HelloWorld.tsx": $HelloWorld,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
